sleep_interval: 1
debug: true
logs:
  level: debug
  timestamp: true

autostart:
  deckboard:
    cmd: ${HOME}/Applications/Deckboard-*.AppImage
    process_name: deckboard
    yolo: true

apps:
  dolphin:
    name: "Dolphin"
    window_title: Dolphin
    scripts:
      skip-checks:
      - runtime
      start:
      - notify-send -a tafker.sh "dolphin got bornzzz"
      stop:
      - notify-send -a tafker.sh "dolphin died. lol"
  deckboard:
    name: "Deckboard"
    process_name: deckboard
    skip-checks:
      - unknown-state
      - runtime
    scripts:
      start:
      - notify-send -a tafker.sh "Deckboard started"
      - sleep 10 && wmctrl -c deckboard
      stop:
      - notify-send -a tafker.sh "Deckboard stopped"
  obs-studio:
    name: "OBS Studio"
    process_name: obs
    scripts:
      start:
      - notify-send -a tafker.sh "obs got bornzzz"
      stop:
      - notify-send -a tafker.sh "obs died for your sins"
  firefox:
    name: "Firefox"
    process_name: firefox
    scripts:
      start:
      - ./scripts/firefox.sh start
      - ./scripts/firefox.sh start2
      - ./scripts/firefox.sh start3
      stop:
      - ./scripts/firefox.sh stop
  zoom:
    name: Zoom
    zoom: true
    scripts:
      start:
      - notify-send -a tafker.sh "IN A ZOOM MEETING"
      stop:
      - notify-send -a tafker.sh "NO LONGER IN A MEETING"
